# Generated by Django 5.0 on 2024-02-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
