# Generated by Django 5.0.2 on 2024-03-26 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0004_artist_album_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amenity', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('addr_city', models.CharField(max_length=255, null=True)),
                ('addr_country', models.CharField(max_length=255, null=True)),
                ('addr_county', models.CharField(max_length=255, null=True)),
                ('addr_housename', models.CharField(max_length=255, null=True)),
                ('addr_housenumber', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=255, null=True)),
                ('addr_street', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('website', models.URLField(max_length=255, null=True)),
                ('wheelchair', models.CharField(max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
