# Generated by Django 5.0.2 on 2024-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0006_pub_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='artist',
        ),
        migrations.AddField(
            model_name='pub',
            name='artist',
            field=models.ManyToManyField(to='worldapp.artist'),
        ),
    ]
