# Generated by Django 5.0.2 on 2024-03-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0007_remove_pub_artist_pub_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='artist',
        ),
        migrations.AddField(
            model_name='pub',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldapp.artist'),
        ),
    ]
