# Generated by Django 5.0.2 on 2024-03-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0009_alter_pub_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldapp.artist'),
        ),
    ]
