# Generated by Django 5.0.2 on 2024-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0010_alter_pub_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='songURL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
