# Generated by Django 5.0.2 on 2024-03-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0011_pub_songurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='songURL',
        ),
        migrations.AddField(
            model_name='pub',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldapp.song'),
        ),
    ]
