# Generated by Django 5.0.2 on 2024-03-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0014_remove_pub_songurl_pub_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='song',
        ),
        migrations.AddField(
            model_name='pub',
            name='songURL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
