# Generated by Django 5.0.2 on 2024-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0015_remove_pub_song_pub_songurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
