# Generated by Django 5.0.2 on 2024-03-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0017_remove_pub_favourite_user_favourite_pubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_pubs',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_pubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourited_by', to='worldapp.pub'),
        ),
    ]
