# Generated by Django 5.0.2 on 2024-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0018_remove_user_favourite_pubs_user_favourite_pubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_pubs',
            field=models.CharField(verbose_name='Favourite Pubs'),
        ),
    ]
