# Generated by Django 5.0.2 on 2024-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0019_alter_user_favourite_pubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_pubs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Favourite Pubs'),
        ),
    ]
