# Generated by Django 5.0.2 on 2024-03-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0020_alter_user_favourite_pubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_pubs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location',
        ),
    ]
