# Generated by Django 5.0.2 on 2024-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0023_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=0, help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='profilepictures/', verbose_name='Profile Picture'),
            preserve_default=False,
        ),
    ]
