# Generated by Django 5.0.2 on 2024-04-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0026_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=0, max_length=50, verbose_name='Genre'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldapp.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldapp.user')),
            ],
        ),
    ]
