# Generated by Django 5.0.2 on 2024-04-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0030_remove_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worldapp.genre', verbose_name='Song Genre'),
            preserve_default=False,
        ),
    ]
