# Generated by Django 5.0.2 on 2024-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0031_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
