# Generated by Django 5.0.2 on 2024-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0033_remove_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
